### ISSUE TITLE
Production Panning method in customised View

### ISSUE THREAD

**Issue by azeemohd786** [AudioKit/Playgrounds#10]
Here I am trying to display panning parameters inside my customised view with slider. I could run your code for,
```
addView(AKSlider(property: "Speed", value: effect.speed, range: 0.1 ... 25) { sliderValue in
                         effect.speed = sliderValue
                   })
```
But I need to run this inside my custom view and slider. How could I do this?

**Comment by aure** [comment]
Numerous examples of this here https://github.com/AudioKit/AudioKit/tree/master/Examples/iOS
