### ISSUE TITLE
Can't build Playgrounds in Xcode 11.5 with Swift 5.2.4

### ISSUE THREAD

**Issue by agawley** [AudioKit/Playgrounds#14]
I get the following error:

Module compiled with Swift 5.0 cannot be imported by the Swift 5.2.4 compiler: /Users/alexgawley/Documents/code/iOS/AudioKit/Playgrounds/Xcode/Pods/AudioKit/macOS/AudioKitUI.framework/Modules/AudioKitUI.swiftmodule/x86_64.swiftmodule

**Comment by megastep** [comment]
The project podfile was still using an old version, I've updated it to use the current one (5.10). See if it helps.

**Comment by agawley** [comment]
Works. Thanks!
