### ISSUE TITLE
Drawbar Organ is buggy

### ISSUE THREAD

**Issue by jwietelmann** [AudioKit/Playgrounds#4]
The drawbar playground is misleadingly simplistic. The AKOscillatorBank stop-note signals for the drawbars collide with those of additionally-played notes. I figured this out the hard way when trying to adapt the example to use with a MIDI controller. Hold key X, then press and release key Y, and all of the overlapping notes of key X turn off.

(I've been trying to construct a workable alternative, but I'm fairly new to AudioKit and haven't mastered the finer points yet. I suspect I need to get a better handle on AKOperation?)

**Comment by aure** [comment]
Hi there, yeah, the playgrounds aren't meant to be performance or production ready musical instruments, just sketches of what's possible with AudioKit and a minimal amount of code. I don't really know if there is an addressable issue here, so I think I will close it.  But, feel free to contact us or even request to be part of the Slack group to talk through the process of making a much better drawbar organ built to your requirements.

**Comment by aure** [comment]
I guess I'll leave this issue open just to let others know this has been discussed.
